const express=require("express");
const router=express.Router();
const Routine=require("../models/routine.js");
const {addRoutine,getRoutine,updateRoutine,deleteRoutine,completeRoutine,getStats}=require("../controllers/routineController.js");
router.post("/add",addRoutine);
router.get("/get",getRoutine);
router.put("/update/:id",updateRoutine);
router.delete("/delete/:id",deleteRoutine);
router.post("/:id/complete",completeRoutine);
router.get("/stats",getStats);
module.exports=router;